eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: eurekeclient-8121
    prefer-ip-address: true  #访问路径可以显示IP地址
server:
  port: 3306
spring:
  application:
    name: eurekaclient