eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: zuul-8080
    prefer-ip-address: true  #访问路径可以显示IP地址
server:
  port: 8080
spring:
  application:
    name: springcloud_zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true